### ISSUE TITLE
Add hyperlinks back into hashtag comments

### ISSUE THREAD

**Issue by julesdepoi** [Cigna/GitRDoneBot#1]
Once our documentation is public, reintroduce hyperlinks that point to those docs to the GRDBot message hashtags.

**Comment by lanaebk** [comment]
Two steps needed to address this:
1. Modify Bot Action descriptions in the README to clearly link the name of the Action with what it does.
2. Add hyperlinks pointing to the README anchors for each Bot Action into the Note classes

**Comment by hannah-reed** [comment]
A fix for this issue is in progress on [update-readme-for-hashtags](https://github.com/Cigna/GitRDoneBot/tree/update-readme-for-hashtags)
